services:
  - type: web
    name: videogpt-tg-bot
    runtime: node
    repo: https://github.com/67LEO/video-gen-ai
    branch: master
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: API_BASE
        value: https://videogpt.dataplazma.com/api/v1
      - key: AES_KEY
        value: nc98463tvkatrx03p59n0598t293v7hb
      - key: ELEVENLABS_BASE
        value: https://api.elevenlabs.io
      - key: PORT
        value: 10000
